// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2wzqeEVdKouN-x3Dvl-vqzqVNo43aMPs',
    appId: '1:423157271684:web:106e27e6413881627d46d1',
    messagingSenderId: '423157271684',
    projectId: 'projet-steam-flutter',
    authDomain: 'projet-steam-flutter.firebaseapp.com',
    storageBucket: 'projet-steam-flutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBK35QinI3x2iLQAWOomJtDrVNYCXs3EaA',
    appId: '1:423157271684:android:c821fd95f701e0eb7d46d1',
    messagingSenderId: '423157271684',
    projectId: 'projet-steam-flutter',
    storageBucket: 'projet-steam-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvHartasdJjkWTPWLp_tKviPX4mQnKjxk',
    appId: '1:423157271684:ios:41f9d21a7b4552b77d46d1',
    messagingSenderId: '423157271684',
    projectId: 'projet-steam-flutter',
    storageBucket: 'projet-steam-flutter.appspot.com',
    iosClientId: '423157271684-lrkr3vtducgbbnngncfvsvmdqlch3v0h.apps.googleusercontent.com',
    iosBundleId: 'com.example.projetv2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvHartasdJjkWTPWLp_tKviPX4mQnKjxk',
    appId: '1:423157271684:ios:41f9d21a7b4552b77d46d1',
    messagingSenderId: '423157271684',
    projectId: 'projet-steam-flutter',
    storageBucket: 'projet-steam-flutter.appspot.com',
    iosClientId: '423157271684-lrkr3vtducgbbnngncfvsvmdqlch3v0h.apps.googleusercontent.com',
    iosBundleId: 'com.example.projetv2',
  );
}
